# Processamento de Dados 
* Semanas 6, 7, 8

In [1]:
import pandas as pd
import numpy as np

CMC Csv
## Attribute Information:

   1. Wife's age                     (numerical)
   2. Wife's education               (categorical)      1=low, 2, 3, 4=high
   3. Husband's education            (categorical)      1=low, 2, 3, 4=high
   4. Number of children ever born   (numerical)
   5. Wife's religion                (binary)           0=Non-Islam, 1=Islam
   6. Wife's now working?            (binary)           0=Yes, 1=No
   7. Husband's occupation           (categorical)      1, 2, 3, 4
   8. Standard-of-living index       (categorical)      1=low, 2, 3, 4=high
   9. Media exposure                 (binary)           0=Good, 1=Not good
   10. Contraceptive method used     (class attribute)  1=No-use 
                                                        2=Long-term
                                                        3=Short-term

In [2]:
cmc_columns = ['wife_age','wife_education', 'husband_education','childrens', 'wife_religion', 'wife_working','husband_occupation','standard_living_index',
              'media_exposure', 'contraceptive_method']
cmc = pd.read_csv('cmc.csv', names=cmc_columns)
cmc.head()

,wife_age,wife_education,husband_education,childrens,wife_religion,wife_working,husband_occupation,standard_living_index,media_exposure,contraceptive_method
0,24,2,3,3,1,1,2,3,0,1
1,45,1,3,10,1,1,3,4,0,1
2,43,2,3,7,1,1,3,4,0,1
3,42,3,2,9,1,1,3,3,0,1
4,36,3,3,8,1,1,3,2,0,1

# Breast CSV
##  Attribute                     Domain
   -- -----------------------------------------
   1. Sample code number            id number
   2. Clump Thickness               1 - 10
   3. Uniformity of Cell Size       1 - 10
   4. Uniformity of Cell Shape      1 - 10
   5. Marginal Adhesion             1 - 10
   6. Single Epithelial Cell Size   1 - 10
   7. Bare Nuclei                   1 - 10
   8. Bland Chromatin               1 - 10
   9. Normal Nucleoli               1 - 10
   
   
  10. Mitoses                       1 - 10
  11. Class:                        (2 for benign, 4 for malignant)

In [12]:
dados = pd.read_csv('breast-cancer.csv', index_col=0)
dados.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
id,,,,,,,,,,,,,,,,,,,,,
842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

### Amostragem simples
A amostragem simples consiste basicamente em extrair objetos, com ou sem reposição,
do conjunto de dados original com igual probabilidade. No primeiro caso, quando há a
reposição, um objeto pode ocorrer mais de uma vez em uma amostra e a probabilidade
de ocorrência de cada objeto mantém-se constante durante todo o processo. No segundo caso , quando não existe reposição, cada objeto poderá acontecer apenas uma vez em uma amostra. Assim, a probabilidade de ocorrência de cada objeto é alterada a cada passo do
processo. O código abaixo apresenta um exemplo para cada caso.

In [ ]:
from IPython.display import display
# gerando uma amostra aleatoria simples de 100 elementos
# da base breast cancer, sem reposicao
display(breast.sample(3))
# gerando uma amostra aleatoria simples de 100 elementos
# da base breast cancer, com reposicao
display(breast.sample(3, replace=True))

### Amostragem estratificada
A amostragem estratificada é tipicamente utilizada quando há o desbalanceamento na
quantidade de exemplos de cada classe em um conjunto de dados. Ou seja, neste cenário,
normalmente uma ou outra classe possuirá uma quantidade de objetos consideravelmente
maior do que as demais. A fim de gerar um classificador que não seja tendencioso para
uma ou mais classes majoritárias ou, de suavizar a dificuldade de modelar alguma das
classes de um problema, a amostragem estratificada pode ser utilizada de duas maneiras.
Na primeira abordagem para amostragem estratificada, o subconjunto a ser extraído contém a mesma quantidade de objetos para cada classe. O código a seguir ilustra,
de maneira simplificada, esse tratamento.

In [10]:
tamanho_amostra = 100
# obtendo as classes da base de dados
classes = dados['diagnosis'].unique()
display(classes)
# calculando a quantidade de amostras por classe
# neste exemplo, serao amostradas as mesmas
# quantidades para cada classe
qtde_por_classe = round(tamanho_amostra / len(classes))
display(qtde_por_classe)
# nesta lista armazenaremos, para cada classe, um
# pandas.DataFrame com suas amostras
amostras_por_classe = []
for c in classes:
    # obtendo os indices do DataFrame
    # cujas instancias pertencem a classe c
    indices_c = dados['diagnosis'] == c
    # extraindo do DataFrame original as observacoes da
    # classe c (obs_c sera um DataFrame tambem)
    obs_c = dados[indices_c]
    # extraindo a amostra da classe c
    # caso deseje-se realizar amostragem com reposicao
    # ou caso len(obs_c) < qtde_por_classe, pode-se
    # informar o parametro replace=True
    amostra_c = obs_c.sample(qtde_por_classe)
    # armazenando a amostra_c na lista de amostras
    amostras_por_classe.append(amostra_c)
    # concatenando as amostras de cada classe em
    # um único DataFrame
    
amostra_estratificada = pd.concat(amostras_por_classe)
amostra_estratificada.head()

array(['M', 'B'], dtype=object)

50

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
id,,,,,,,,,,,,,,,,,,,,,
8610637,M,18.05,16.15,120.20,1006.0,0.10650,0.21460,0.16840,0.10800,0.2152,...,18.91,150.10,1610.0,0.14780,0.5634,0.3786,0.21020,0.3751,0.11080,NaN
877159,M,18.08,21.84,117.40,1024.0,0.07371,0.08642,0.11030,0.05778,0.1770,...,24.70,129.10,1228.0,0.08822,0.1963,0.2535,0.09181,0.2369,0.06558,NaN
868202,M,12.77,22.47,81.72,506.3,0.09055,0.05761,0.04711,0.02704,0.1585,...,33.37,92.04,653.6,0.14190,0.1523,0.2177,0.09331,0.2829,0.08067,NaN
926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,26.40,166.10,2027.0,0.14100,0.2113,0.4107,0.22160,0.2060,0.07115,NaN
86355,M,22.27,19.67,152.80,1509.0,0.13260,0.27680,0.42640,0.18230,0.2556,...,28.01,206.80,2360.0,0.17010,0.6997,0.9608,0.29100,0.4055,0.09789,NaN

In [13]:
# removendo exemplos redundantes
# observe que o resultado sera a base original
# o parametro inplace determina se a alteracao deve
# ocorrer no proprio DataFrame
# portanto, caso inplace=False, a funcao drop_duplicates
# retorna uma copia de breast_cancer_red com os exemplos
# redundantes removidos
display(dados.shape)
dados.drop_duplicates(inplace=True)
display(dados.shape)

(569, 32)

(569, 32)

In [16]:
# dividindo o atributo 'mean_radius' em 10 faixas
bins = pd.qcut(dados['radius_mean'], 10)
# a quantidade de valores aproximadamente igual em
# cada faixa pode ser comprovada pelo metodo
# value_counts
display(bins.value_counts())
# O metodo groupby permite que valores contidos na
# coluna de um DataFrame sejam agrupados segundo
# algum criterio.
# Neste exemplo, a coluna 'mean_radius' sera agrupada
# pelas faixas definidas pelo metodo qcut.
grupos = dados['radius_mean'].groupby(bins)
# obtendo a media de cada faixa
medias = grupos.mean()
# Obtendo a nova coluna.
# O metodo apply recebe como parametro uma funcao,
# aplica tal funcao a todos os seus elements e retorna
# um pandas.Series contendo os resultados.
# Neste caso, cada elemento de bins consiste
# no intervalo que o respectivo valor de 'mean_radius'
# pertence e, assim, a funcao informada em apply
# retornara a respectiva media de cada intervalo.
novo_mean_radius = bins.apply(lambda x : medias[x])
# por fim, a coluna 'mean_radius' do DataFrame original
# eh atualizada
novo_mean_radius

(17.068, 19.53]                58
(6.9799999999999995, 10.26]    58
(15.056, 17.068]               57
(14.058, 15.056]               57
(12.726, 13.37]                57
(12.012, 12.726]               57
(11.366, 12.012]               57
(19.53, 28.11]                 56
(13.37, 14.058]                56
(10.26, 11.366]                56
Name: radius_mean, dtype: int64

id
842302      18.324483
842517      21.453750
84300903    21.453750
84348301    11.691754
84358402    21.453750
              ...
926424      21.453750
926682      21.453750
926954      15.914561
927241      21.453750
92751        9.342052
Name: radius_mean, Length: 569, dtype: category
Categories (10, float64): [9.342052 < 10.951071 < 11.691754 < 12.357018 ... 14.605088 < 15.914561 < 18.324483 < 21.453750]